name: CustomItemAPI
version: 0.2
main: com.github.firewolf8385.customitemapi.CustomItemAPI
api-version: 1.18
authors: [ firewolf8385 ]
website: github.com/firewolf8385

commands:
  items:
    description: Main plugin command.
    usage: /<command>
    aliases: [customitems,ci,customitemapi,ciapi]